services:
  omniroom:
    image: 4gjr3z1t/omniroom:dev
    hostname: omniroom
    container_name: omniroom
    environment:
      - PORT=8080
      - UDP_MUX_PORT=4004
      - NAT_IPS=<public_ip>
    ports:
      - 8080:8080
      - 4004:4004
